TK_basdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import login.urls as account
import wawancara.urls as wawancara
import pengumuman.urls as pengumuman
import pembayaran.urls as pembayaran
import pendaftaran_skema.urls as pendaftaran_skema
import informasi_beasiswa_aktif.urls as informasi_beasiswa_aktif
from login.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include(account, namespace='account')),
    url(r'^wawancara/', include(wawancara, namespace='wawancara')),
    url(r'^pengumuman/', include(pengumuman, namespace='pengumuman')),
    url(r'^pembayaran/', include(pembayaran, namespace='pembayaran')),
    url(r'^pendaftaran_skema/', include(pendaftaran_skema, namespace='pendaftaran_skema')),
    url(r'^informasi_beasiswa_aktif/', include(informasi_beasiswa_aktif, namespace='informasi_beasiswa_aktif')),
    url(r'^$', home, name='home'),
    
]

login/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^login/', indexLogin, name='login'),
    url(r'^submit-login', login, name='submitLogin'),
    url(r'^logout/', logout, name='logout'),
    url(r'^register/', register, name='register'),
    url(r'^submit-mahasiswa', submit_mahasiswa, name='submit-mahasiswa'),
    url(r'^submit-donatur-individu', submit_individual_donor, name='submit-donatur-individual'),
    url(r'^submit-donatur-yayasan', submit_yayasan, name='submit-donatur-yayasan'),
]

pendaftaran_skema/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^daftar_paket_beasiswa/', daftar_paket, name='daftar_paket'),
    url(r'^pendaftaran-sukses/', sukses, name='sukses'),
    
]

pendaftaran_skema/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Admin(models.Model):
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username', primary_key=True)

    class Meta:
        managed = False
        db_table = 'admin'


class Donatur(models.Model):
    nomor_identitas = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    npwp = models.CharField(max_length=20)
    no_telp = models.CharField(max_length=20, blank=True, null=True)
    alamat = models.CharField(max_length=50)
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username')

    class Meta:
        managed = False
        db_table = 'donatur'


class IndividualDonor(models.Model):
    nik = models.CharField(primary_key=True, max_length=16)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'individual_donor'


class Mahasiswa(models.Model):
    npm = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp = models.CharField(max_length=20, blank=True, null=True)
    alamat_tinggal = models.CharField(max_length=50)
    alamat_domisili = models.CharField(max_length=50)
    nama_bank = models.CharField(max_length=50)
    no_rekening = models.CharField(max_length=20)
    nama_pemilik = models.CharField(max_length=20)
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username')

    class Meta:
        managed = False
        db_table = 'mahasiswa'


class Pembayaran(models.Model):
    urutan = models.IntegerField(primary_key=True)
    kode_skema_beasiswa = models.IntegerField()
    no_urut_skema_beasiswa_aktif = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='no_urut_skema_beasiswa_aktif')
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    keterangan = models.CharField(max_length=50)
    tgl_bayar = models.CharField(max_length=50)
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'pembayaran'
        unique_together = (('urutan', 'kode_skema_beasiswa', 'no_urut_skema_beasiswa_aktif', 'npm'),)


class Pendaftaran(models.Model):
    no_urut = models.IntegerField(primary_key=True)
    kode_skema_beasiswa = models.ForeignKey('SkemaBeasiswa', models.DO_NOTHING, db_column='kode_skema_beasiswa')
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    waktu_daftar = models.DateTimeField()
    status_daftar = models.CharField(max_length=20)
    status_terima = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'pendaftaran'
        unique_together = (('no_urut', 'kode_skema_beasiswa', 'npm'),)


class Pengguna(models.Model):
    username = models.CharField(primary_key=True, max_length=20)
    password = models.CharField(max_length=20)
    role = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'pengguna'


class Pengumuman(models.Model):
    tanggal = models.DateField(primary_key=True)
    no_urut_skema_beasiswa_aktif = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='no_urut_skema_beasiswa_aktif')
    kode_skema_beasiswa = models.IntegerField()
    username = models.ForeignKey(Pengguna, models.DO_NOTHING, db_column='username')
    judul = models.CharField(max_length=20)
    isi = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'pengumuman'
        unique_together = (('tanggal', 'no_urut_skema_beasiswa_aktif', 'kode_skema_beasiswa', 'username'),)


class RiwayatAkademik(models.Model):
    no_urut = models.IntegerField(primary_key=True)
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    semester = models.CharField(max_length=1)
    tahun_ajaran = models.CharField(max_length=9)
    jumlah_sks = models.IntegerField()
    ips = models.FloatField()
    lampiran = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'riwayat_akademik'
        unique_together = (('no_urut', 'npm'),)


class SkemaBeasiswa(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    jenis = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=50)
    no_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='no_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'skema_beasiswa'


class SkemaBeasiswaAktif(models.Model):
    kode_skema_beasiswa = models.ForeignKey(SkemaBeasiswa, models.DO_NOTHING, db_column='kode_skema_beasiswa', primary_key=True)
    no_urut = models.IntegerField()
    tgl_mulai_pendaftaran = models.DateField()
    tgl_tutup_pendaftaran = models.DateField()
    periode_penerimaan = models.CharField(max_length=50)
    status = models.CharField(max_length=20)
    jumlah_pendaftar = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'skema_beasiswa_aktif'
        unique_together = (('kode_skema_beasiswa', 'no_urut'),)


class SyaratBeasiswa(models.Model):
    kode_beasiswa = models.ForeignKey(SkemaBeasiswa, models.DO_NOTHING, db_column='kode_beasiswa', primary_key=True)
    syarat = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'syarat_beasiswa'
        unique_together = (('kode_beasiswa', 'syarat'),)


class TempatWawancara(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    lokasi = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tempat_wawancara'


class Wawancara(models.Model):
    no_urut_skema_beasiswa_aktif = models.ForeignKey(SkemaBeasiswaAktif, models.DO_NOTHING, db_column='no_urut_skema_beasiswa_aktif', primary_key=True)
    kode_skema_beasiswa = models.IntegerField()
    jadwal = models.DateTimeField()
    kode_tempat_wawancara = models.ForeignKey(TempatWawancara, models.DO_NOTHING, db_column='kode_tempat_wawancara')

    class Meta:
        managed = False
        db_table = 'wawancara'
        unique_together = (('no_urut_skema_beasiswa_aktif', 'kode_skema_beasiswa', 'jadwal'),)


class Yayasan(models.Model):
    no_sk_yayasan = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp_cp = models.CharField(max_length=20, blank=True, null=True)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'yayasan'

pendaftaran_skema/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
from django.db import connection
from django.contrib import messages

def index(request):
    response = {}
    if ('username' in request.session.keys()):
        response['role'] = request.session['role']
        if ('nama' in request.session.keys()):
            response['nama'] = request.session['nama']
        response['username'] = request.session['username']

        if (response['role'] == 'yayasan' or response['role'] == 'individual_donor'):
            return render(request, 'pendaftaran_skema.html')

    else:
        return HttpResponseRedirect(reverse('account:login'))

def sukses(request):
    response = {}
    if ('username' in request.session.keys()):
        response['role'] = request.session['role']
        if ('nama' in request.session.keys()):
            response['nama'] = request.session['nama']
        response['username'] = request.session['username']
        return render(request, 'sukses.html')
    else:
        return HttpResponseRedirect(reverse('account:login'))


@csrf_protect
@require_http_methods(["POST"])
def daftar_paket(request):
    response = {}
    if ('username' in request.session.keys()):
        response['role'] = request.session['role']
        if ('nama' in request.session.keys()):
            response['nama'] = request.session['nama']
        response['username'] = request.session['username']

        if (response['role'] == 'yayasan' or response['role'] == 'individual_donor'):
            username=request.session['username']
            
            print(request.POST)

            kode = request.POST.get('kode')
            nama= request.POST.get('nama')
            jenis= request.POST.get('jenis')
            deskripsi = request.POST.get('deskripsi')
            syarat = request.POST.get('syarat')
            print(kode)
            cursor = connection.cursor()
            cursor.execute("SELECT * FROM skema_beasiswa WHERE kode=%s",(kode,))
            result = cursor.fetchone()
            if(result):
                if len(result)>0:
                    messages.error(request, "Pendaftaran Gagal: Kode " +kode+" sudah ada")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

            

            cursor = connection.cursor()
            cursor.execute("SELECT nomor_identitas from donatur where username='"+username+"'")
            result = cursor.fetchone()
            no_id = result[0]

            

            query = "INSERT INTO skema_beasiswa(kode,nama,jenis,deskripsi,no_identitas_donatur) values (%s, %s, %s, %s, %s)"
            data = (kode, nama, jenis, deskripsi, no_id)
            cursor.execute(query, data)

            cursor = connection.cursor()
            query = "INSERT INTO syarat_beasiswa (kode_beasiswa,syarat) values ('"+kode+"','"+syarat+"')"
            cursor.execute(query)

            messages.success(request, "Pendaftaran Berhasil")

            return HttpResponseRedirect(reverse('pendaftaran_skema:sukses'))
    else:
        return HttpResponseRedirect(reverse('account:login'))

pendaftaran_skema/templates/pendaftaran_skema.html
{% extends "layout/base.html" %}
{% block title %}
Pendafaran Skema Beasiswa
{% endblock %}

{% block content %}
<div class="c15572">
    <br></br>
        <b>FORM PENDAFTARAN PAKET BEASISWA</b>
    <br></br>
      </div>
      <div class="c10462">
      </div>
      <div class="c10462">
      </div>
      <div class="c10462">
      </div>
      <form class="form" method="POST" action="{% url 'pendaftaran_skema:daftar_paket'%}"> 
        {% csrf_token %}
        <div class="form-group">
          <div id="ij1twq" class="row">
            <div id="ixain6" class="cell">
              <p align="left" style="font-size:17px">Kode</p>
            </div>
            <div class="cell">
              <input name="kode" required class="input"/>
            </div>
          </div>
          <div class="row c7717">
            <div id="iumm9a" class="cell">
                  <p align="left" style="font-size:17px">Nama Paket Beasiswa</p>
            </div>
            <div class="cell">
              <input name="nama" required class="input"/>
            </div>
          </div>
          <div class="row c7717">
            <div id="ivuyvb" class="cell">
                  <p align="left" style="font-size:17px">Jenis Paket Beasiswa</p>
            </div>
            <div class="cell">
              <select name="jenis" class="select"><option value="">- Select option -</option><option value="1">Beasiswa prestasi akademik</option><option value="2">Beasiswa bantuan belajar</option><option value="3">Beasiswa tugas akhir</option></select>
            </div>
          </div>
          <div class="row c7717">
            <div id="irs8aq" class="cell">
                  <p align="left" style="font-size:17px">Deskripsi</p>
            </div>
            <div class="cell">
              <input name="deskripsi" required class="input"/>
            </div>
          </div>
          <div class="row c7717">
            <div id="ixoftq" class="cell">
                  <p align="left" style="font-size:17px">Syarat Beasiswa</p>
            </div>
            <div class="cell">
              <input name="syarat" required class="input"/>
            </div>
          </div>
          <div class="form-group">
            <button type="submit" class="button">Submit</button>
          </div>
        </div>
      </form>
{% endblock %}

pendaftaran_skema/templates/sukses.html
{% extends "layout/base.html" %}
{% block title %}
Register Success
{% endblock %}
{% block content %}
<br><br><br>
<div class="w3-container">
      <center>
          <p><strong>Pendaftaran Beasiswa Berhasil</strong></p>
      </center>
  </div>

{% endblock %}

pendaftaran_skema/templates/tambah_beasiswa.html
{% extends "layout/base.html" %}
{% block title %}
Pendafaran Skema Beasiswa
{% endblock %}

{% block content %}
<div class="c16245">
<br> </br>
<b id="i3g65h">FORM PENDAFTARAN TAMBAH BEASISWA DARI PAKET</b>
<br> </br>
</div><div class="c10462"></div><div class="c10462">
</div><div class="c10462">
</div><form class="form"><div class="row" id="i0mni9"><div class="cell" id="i50cid"><p align="left" style="font-size:17px">Kode Beasiswa</p></div><div class="cell"><select required="" class="select"><option value="">- Select option -</option><option value="1">Option 1</option><option value="2">2</option><option value="3">3</option></select></div></div><div class="row c16739"><div class="cell" id="igsnef"><p align="left" style="font-size:17px">Nomor Urut</p></div><div class="cell"><input required="" type="text" class="input"/></div></div><div class="row c16739"><div class="cell" id="ita0vf"><p align="left" style="font-size:17px">Tanggal Mulai Pendaftaran</p></div><div class="cell"><input type="date" value="<?php echo date('Y-m-d'); ?>" required="" id="ivpd3jm" class="c5835"/></div></div><div class="row c16739"><div class="cell" id="i5wesq"><p align="left" style="font-size:17px">Tanggal Tutup Pendaftaran</p>
</div><div class="cell"><input type="date" value="<?php echo date('Y-m-d'); ?>" required="" class="c18413"/></div></div><div class="form-group"></div><div class="form-group"></div><div class="form-group"></div><div class="form-group"><button type="submit" class="button">Submit</button></div></form></section><section class="flex-sect"><div class="c10462">
</div><div class="c10462">
{% endblock %}